name: Scrape

on:
  schedule:
    - cron: "* * * * *" # every minute
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - run: pip install pandas finnhub-python
    - name: Run scraper
      run: python3 app.py
