name: Scrape

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - run: pip install pandas finnhub-python
    - name: Run scraper
      run: python3 app.py
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data" 	
    - name: Push	
      run: git push
